import { Entity, PrimaryGeneratedColumn, Column, BaseEntity } from 'typeorm';
import { JudgingVote } from './judgingVote';
import { Team } from './team';

@Entity()
export class Judge extends BaseEntity {
  constructor() {
    super();

    this.id = (undefined as unknown) as number; // Auto-generated by database, so this gets around TS Strict Mode
    this.visitedTeams = [];
    this.currentTeam = undefined;
  }

  @PrimaryGeneratedColumn()
  id: number;

  @Column('simple-json')
  visitedTeams: number[];

  @Column({ nullable: true })
  currentTeam?: number;

  @Column({ nullable: true })
  previousTeam?: number;

  async getNextTeam(): Promise<Team | undefined> {
    const newTeam = await Team.getNextAvailableTeamExcludingTeams(this.visitedTeams);
    this.currentTeam = newTeam ? newTeam.id : undefined;
    await this.save();
    return newTeam;
  }

  async continue(): Promise<void> {
    await this.recordCurrentTeamAndSave();
  }

  async skip(): Promise<void> {
    const updatePrevious = false;
    await this.recordCurrentTeamAndSave(updatePrevious);
  }

  async vote(currentTeamChosen: boolean): Promise<void> {
    if (!this.currentTeam) {
      throw new Error('No current team to vote on');
    }

    // Create a new vote object with the outcome of the vote
    await new JudgingVote(this.visitedTeams[this.visitedTeams.length - 1], this.currentTeam, currentTeamChosen).save();
    await this.recordCurrentTeamAndSave();
  }

  async recordCurrentTeamAndSave(updatePrevious = true): Promise<void> {
    if (!this.currentTeam) {
      throw new Error('No current team to record');
    }

    this.visitedTeams.push(this.currentTeam);
    if (updatePrevious) {
      this.previousTeam = this.currentTeam;
    }
    const currentTeam = await Team.findOneOrFail(this.currentTeam);
    await currentTeam.decrementActiveJudgeCount();
    await currentTeam.incrementJudgeVisits();
    this.currentTeam = undefined;
    await this.save();
  }
}
