import { Entity, PrimaryGeneratedColumn, Column, BaseEntity } from 'typeorm';

@Entity()
export class Subscriber extends BaseEntity {
  constructor(slackId: string) {
    super();

    this.id = (undefined as unknown) as number; // Auto-generated by database, so this gets around TS Strict Mode
    this.slackId = slackId;
    this.isActive = true;
  }

  @PrimaryGeneratedColumn()
  id: number;

  @Column({ unique: true })
  slackId: string;

  @Column({ default: true })
  isActive: boolean;
}
