name: Deploy

on:
  push:
    branches: 
      - migration/heroku-cli-deployment
      - master

jobs:
  release:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v1
    - name: Use Heroku CLI
      uses: actions/heroku@master
    - name: create app if it doesn't exist
      uses: actions/heroku@master
      continue-on-error: true
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      with:
        args: create ${{ secrets.APP_NAME }}
    - name: create addons if they doesn't exist
      uses: actions/heroku@master
      continue-on-error: true
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      with:
        args: addons:create heroku-postgresql:hobby-dev --as TYPEORM_URL --name ${{ secrets.APP_NAME }}-postgres
    - name: add remote
      uses: actions/heroku@master
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      with:
        args: git:remote -a ${{ secrets.APP_NAME }}
    - name: set env variables
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        heroku config:set SLACK_SIGNING_SECRET=${{ secrets.SLACK_SIGNING_SECRET }}
        heroku config:set SLACK_BOT_TOKEN=${{ secrets.SLACK_BOT_TOKEN }}
    - name: deploy
      run: |
        git config --global user.name ""
        git config --global user.password ${{ secrets.HEROKU_API_KEY }}
        git push heroku HEAD:master

    
