# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.

name: Labeler
on:
 schedule:
 - cron: "0/15 * * * *"

jobs:
  label:

    runs-on: ubuntu-latest

    steps:
    - name: Labeler
      uses: actions/labeler@v3
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
