name: Release to Production

on:
  push:
    branches: [main]

env:
  DOCKER_REGISTRY: ghcr.io

jobs:
  release:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Restore Docker cache
        uses: actions/cache@v2
        env:
          cache-base: v1-${{ runner.os }}-cache-docker
        with:
          path: /tmp/.buildx-cache
          key: ${{ env.cache-base }}-${{ github.sha }}
          restore-keys: |
            ${{ env.cache-base }}-

      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Image SHA tag
        id: getTag
        run: echo ::set-output name=shaImageTag::sha-${GITHUB_SHA::8}

      - name: Get Docker Image Name
        uses: actions/github-script@v4
        id: dockerImageName
        with:
          result-encoding: string
          script: return "${{ github.repository }}".toLowerCase();

      - name: Docker build
        uses: docker/build-push-action@v2
        env:
          DOCKER_IMAGE: ${{ env.DOCKER_REGISTRY }}/${{ steps.dockerImageName.outputs.result }}
        with:
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:${{ steps.getTag.outputs.shaImageTag }}
            ${{ env.DOCKER_IMAGE }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
