name: Release to Production

on:
  push:
    branches: [main, v2]
  workflow_dispatch:

env:
  DOCKER_REGISTRY: registry.heroku.com
  HEROKU_PROCESS_TYPE: web

jobs:
  release:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Restore Docker cache
        uses: actions/cache@v2
        env:
          cache-base: v1-${{ runner.os }}-cache-docker
        with:
          path: /tmp/.buildx-cache
          key: ${{ env.cache-base }}-${{ github.sha }}
          restore-keys: |
            ${{ env.cache-base }}-

      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: _
          password: ${{ secrets.HEROKU_API_KEY }}

      - name: Docker build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.DOCKER_REGISTRY }}/${{ secrets.APP_NAME }}/${{ env.HEROKU_PROCESS_TYPE }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Heroku Set Config and release
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          APP_URL=`heroku apps:info ${{ secrets.APP_NAME }} -s | grep web_url | cut -d= -f2`
          APP_URL=${APP_URL%/}

          heroku config:set --app ${{ secrets.APP_NAME }} \
            NODE_ENV=production \
            APP_URL=$APP_URL \
            \
            SESSION_SECRET=${{ secrets.SESSION_SECRET }} \
            DISCORD_CLIENT_ID=${{ secrets.DISCORD_CLIENT_ID }} \
            DISCORD_CLIENT_SECRET=${{ secrets.DISCORD_CLIENT_SECRET }} \
            DISCORD_GUILD_ID=${{ secrets.DISCORD_GUILD_ID }} \
            DISCORD_BOT_TOKEN=${{secrets.DISCORD_BOT_TOKEN}}

          heroku container:release ${{ env.HEROKU_PROCESS_TYPE }} --app ${{ secrets.APP_NAME }}
