name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NODE_VERSION: 14

jobs:
  checks:
    name: Test Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Restore node_modules
        uses: actions/cache@v2
        id: restore-node-modules
        env:
          cache-name: node_modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}

      - name: Restore Yarn cache
        uses: actions/cache@v2
        if: steps.restore-node-modules.outputs.cache-hit != 'true'
        env:
          cache-name: yarn-cache
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-

      - name: Install dependencies
        if: steps.restore-node-modules.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Setup project
        run: yarn setup

      - name: Run Test Coverage
        run: yarn test:coverage
